# Auto-generated by generator/csr_test_generator.py
# Source CSR map: rampart_i2c_csr.hjson

import cocotb
from cocotb.clock import Clock
from cocotb.triggers import RisingEdge

DUT_NAME = 'rampart_i2c'
MAX_WAIT_CYCLES = 200
PATTERNS = [0x55555555, 0xAAAAAAAA]

REGISTERS = [
    {
        'name': 'CTRL',
        'offset': 0x00000000,
        'reset': 0x00000000,
        'reg_access': 'rw',
        'rw_mask': 0x00000007,
        'ro_mask': 0x00000000,
        'w1c_mask': 0x00000000,
        'wo_mask': 0x00000000,
        'w1s_mask': 0x00000000,
        'writable_mask': 0x00000007,
        'readable': True,
        'reset_stable': True,
        'ro_stable': False,
        'rw_stable': True,
        'decode_candidate': True,
    },
    {
        'name': 'STATUS',
        'offset': 0x00000004,
        'reset': 0x000000EA,
        'reg_access': 'ro',
        'rw_mask': 0x00000000,
        'ro_mask': 0x000003FF,
        'w1c_mask': 0x00000000,
        'wo_mask': 0x00000000,
        'w1s_mask': 0x00000000,
        'writable_mask': 0x00000000,
        'readable': True,
        'reset_stable': False,
        'ro_stable': False,
        'rw_stable': False,
        'decode_candidate': False,
    },
    {
        'name': 'RDATA',
        'offset': 0x00000008,
        'reset': 0x00000000,
        'reg_access': 'ro',
        'rw_mask': 0x00000000,
        'ro_mask': 0x000000FF,
        'w1c_mask': 0x00000000,
        'wo_mask': 0x00000000,
        'w1s_mask': 0x00000000,
        'writable_mask': 0x00000000,
        'readable': True,
        'reset_stable': True,
        'ro_stable': True,
        'rw_stable': False,
        'decode_candidate': False,
    },
    {
        'name': 'FDATA',
        'offset': 0x0000000C,
        'reset': 0x00000000,
        'reg_access': 'wo',
        'rw_mask': 0x00000000,
        'ro_mask': 0x00000000,
        'w1c_mask': 0x00000000,
        'wo_mask': 0x00001FFF,
        'w1s_mask': 0x00000000,
        'writable_mask': 0x00001FFF,
        'readable': False,
        'reset_stable': False,
        'ro_stable': False,
        'rw_stable': False,
        'decode_candidate': False,
    },
    {
        'name': 'FIFO_CTRL',
        'offset': 0x00000010,
        'reset': 0x00000000,
        'reg_access': 'wo',
        'rw_mask': 0x00000000,
        'ro_mask': 0x00000000,
        'w1c_mask': 0x00000000,
        'wo_mask': 0x0000000F,
        'w1s_mask': 0x00000000,
        'writable_mask': 0x0000000F,
        'readable': False,
        'reset_stable': False,
        'ro_stable': False,
        'rw_stable': False,
        'decode_candidate': False,
    },
    {
        'name': 'FIFO_STATUS',
        'offset': 0x00000014,
        'reset': 0x00000000,
        'reg_access': 'ro',
        'rw_mask': 0x00000000,
        'ro_mask': 0x0FFFFFFF,
        'w1c_mask': 0x00000000,
        'wo_mask': 0x00000000,
        'w1s_mask': 0x00000000,
        'writable_mask': 0x00000000,
        'readable': True,
        'reset_stable': False,
        'ro_stable': False,
        'rw_stable': False,
        'decode_candidate': False,
    },
    {
        'name': 'OVRD',
        'offset': 0x00000018,
        'reset': 0x00000000,
        'reg_access': 'rw',
        'rw_mask': 0x00000007,
        'ro_mask': 0x00000000,
        'w1c_mask': 0x00000000,
        'wo_mask': 0x00000000,
        'w1s_mask': 0x00000000,
        'writable_mask': 0x00000007,
        'readable': True,
        'reset_stable': False,
        'ro_stable': False,
        'rw_stable': False,
        'decode_candidate': False,
    },
    {
        'name': 'TIMING0',
        'offset': 0x0000001C,
        'reset': 0x00F000F0,
        'reg_access': 'rw',
        'rw_mask': 0xFFFFFFFF,
        'ro_mask': 0x00000000,
        'w1c_mask': 0x00000000,
        'wo_mask': 0x00000000,
        'w1s_mask': 0x00000000,
        'writable_mask': 0xFFFFFFFF,
        'readable': True,
        'reset_stable': False,
        'ro_stable': False,
        'rw_stable': True,
        'decode_candidate': True,
    },
    {
        'name': 'TIMING1',
        'offset': 0x00000020,
        'reset': 0x00080008,
        'reg_access': 'rw',
        'rw_mask': 0xFFFFFFFF,
        'ro_mask': 0x00000000,
        'w1c_mask': 0x00000000,
        'wo_mask': 0x00000000,
        'w1s_mask': 0x00000000,
        'writable_mask': 0xFFFFFFFF,
        'readable': True,
        'reset_stable': False,
        'ro_stable': False,
        'rw_stable': True,
        'decode_candidate': True,
    },
    {
        'name': 'TIMING2',
        'offset': 0x00000024,
        'reset': 0x00180018,
        'reg_access': 'rw',
        'rw_mask': 0xFFFFFFFF,
        'ro_mask': 0x00000000,
        'w1c_mask': 0x00000000,
        'wo_mask': 0x00000000,
        'w1s_mask': 0x00000000,
        'writable_mask': 0xFFFFFFFF,
        'readable': True,
        'reset_stable': False,
        'ro_stable': False,
        'rw_stable': True,
        'decode_candidate': True,
    },
    {
        'name': 'TIMING3',
        'offset': 0x00000028,
        'reset': 0x00060006,
        'reg_access': 'rw',
        'rw_mask': 0xFFFFFFFF,
        'ro_mask': 0x00000000,
        'w1c_mask': 0x00000000,
        'wo_mask': 0x00000000,
        'w1s_mask': 0x00000000,
        'writable_mask': 0xFFFFFFFF,
        'readable': True,
        'reset_stable': False,
        'ro_stable': False,
        'rw_stable': True,
        'decode_candidate': True,
    },
    {
        'name': 'TIMING4',
        'offset': 0x0000002C,
        'reset': 0x00180018,
        'reg_access': 'rw',
        'rw_mask': 0xFFFFFFFF,
        'ro_mask': 0x00000000,
        'w1c_mask': 0x00000000,
        'wo_mask': 0x00000000,
        'w1s_mask': 0x00000000,
        'writable_mask': 0xFFFFFFFF,
        'readable': True,
        'reset_stable': False,
        'ro_stable': False,
        'rw_stable': True,
        'decode_candidate': True,
    },
    {
        'name': 'TARGET_ID',
        'offset': 0x00000030,
        'reset': 0x00000000,
        'reg_access': 'rw',
        'rw_mask': 0x00003FFF,
        'ro_mask': 0x00000000,
        'w1c_mask': 0x00000000,
        'wo_mask': 0x00000000,
        'w1s_mask': 0x00000000,
        'writable_mask': 0x00003FFF,
        'readable': True,
        'reset_stable': True,
        'ro_stable': False,
        'rw_stable': True,
        'decode_candidate': True,
    },
    {
        'name': 'ACQDATA',
        'offset': 0x00000034,
        'reset': 0x00000000,
        'reg_access': 'ro',
        'rw_mask': 0x00000000,
        'ro_mask': 0x000003FF,
        'w1c_mask': 0x00000000,
        'wo_mask': 0x00000000,
        'w1s_mask': 0x00000000,
        'writable_mask': 0x00000000,
        'readable': True,
        'reset_stable': True,
        'ro_stable': True,
        'rw_stable': False,
        'decode_candidate': False,
    },
    {
        'name': 'TXDATA',
        'offset': 0x00000038,
        'reset': 0x00000000,
        'reg_access': 'wo',
        'rw_mask': 0x00000000,
        'ro_mask': 0x00000000,
        'w1c_mask': 0x00000000,
        'wo_mask': 0x000000FF,
        'w1s_mask': 0x00000000,
        'writable_mask': 0x000000FF,
        'readable': False,
        'reset_stable': False,
        'ro_stable': False,
        'rw_stable': False,
        'decode_candidate': False,
    },
    {
        'name': 'HOST_TIMEOUT_CTRL',
        'offset': 0x0000003C,
        'reset': 0x00000000,
        'reg_access': 'rw',
        'rw_mask': 0xFFFFFFFF,
        'ro_mask': 0x00000000,
        'w1c_mask': 0x00000000,
        'wo_mask': 0x00000000,
        'w1s_mask': 0x00000000,
        'writable_mask': 0xFFFFFFFF,
        'readable': True,
        'reset_stable': False,
        'ro_stable': False,
        'rw_stable': False,
        'decode_candidate': False,
    },
    {
        'name': 'INTR_STATE',
        'offset': 0x00000040,
        'reset': 0x00000000,
        'reg_access': 'w1c',
        'rw_mask': 0x00000000,
        'ro_mask': 0x00000000,
        'w1c_mask': 0x0000FFFF,
        'wo_mask': 0x00000000,
        'w1s_mask': 0x00000000,
        'writable_mask': 0x0000FFFF,
        'readable': True,
        'reset_stable': False,
        'ro_stable': False,
        'rw_stable': False,
        'decode_candidate': False,
    },
    {
        'name': 'INTR_ENABLE',
        'offset': 0x00000044,
        'reset': 0x00000000,
        'reg_access': 'rw',
        'rw_mask': 0x0000FFFF,
        'ro_mask': 0x00000000,
        'w1c_mask': 0x00000000,
        'wo_mask': 0x00000000,
        'w1s_mask': 0x00000000,
        'writable_mask': 0x0000FFFF,
        'readable': True,
        'reset_stable': True,
        'ro_stable': False,
        'rw_stable': False,
        'decode_candidate': False,
    },
    {
        'name': 'INTR_TEST',
        'offset': 0x00000048,
        'reset': 0x00000000,
        'reg_access': 'rw',
        'rw_mask': 0x0000FFFF,
        'ro_mask': 0x00000000,
        'w1c_mask': 0x00000000,
        'wo_mask': 0x00000000,
        'w1s_mask': 0x00000000,
        'writable_mask': 0x0000FFFF,
        'readable': True,
        'reset_stable': True,
        'ro_stable': False,
        'rw_stable': False,
        'decode_candidate': False,
    },
]

W1C_SETTERS = {
    'INTR_STATE': 0x00000048,
}


def _logic_to_int(value_obj):
    """Convert simulator logic values to int, mapping X/Z to 0."""

    try:
        return int(value_obj)
    except ValueError:
        bits = str(value_obj).lower()
        cleaned = "".join("0" if ch in ("x", "z") else ch for ch in bits)
        return int(cleaned, 2)


class TlUlDriver:
    """Minimal TL-UL frontdoor CSR driver for generated tests."""

    def __init__(self, dut, clk_signal="clk_i", rst_signal="rst_ni"):
        self.dut = dut
        self.clk = getattr(dut, clk_signal)
        self.rst = getattr(dut, rst_signal)

    def idle_bus(self):
        self.dut.tl_a_valid_i.value = 0
        self.dut.tl_a_opcode_i.value = 0
        self.dut.tl_a_address_i.value = 0
        self.dut.tl_a_data_i.value = 0
        self.dut.tl_a_mask_i.value = 0
        self.dut.tl_a_source_i.value = 0
        self.dut.tl_a_size_i.value = 0
        self.dut.tl_d_ready_i.value = 0

    async def reset(self, cycles=8):
        self.idle_bus()
        self.rst.value = 0
        for _ in range(cycles):
            await RisingEdge(self.clk)
        self.rst.value = 1
        for _ in range(2):
            await RisingEdge(self.clk)

    async def _wait_for(self, signal, expected=1, timeout_cycles=MAX_WAIT_CYCLES):
        for _ in range(timeout_cycles):
            if _logic_to_int(signal.value) == expected:
                return True
            await RisingEdge(self.clk)
        return False

    async def write_reg(self, addr, data, mask=0xF, source=0, allow_error=False):
        self.dut.tl_a_valid_i.value = 1
        self.dut.tl_a_opcode_i.value = 0  # PutFullData
        self.dut.tl_a_address_i.value = addr
        self.dut.tl_a_data_i.value = data & 0xFFFFFFFF
        self.dut.tl_a_mask_i.value = mask
        self.dut.tl_a_source_i.value = source
        self.dut.tl_a_size_i.value = 2
        self.dut.tl_d_ready_i.value = 1

        await RisingEdge(self.clk)
        assert await self._wait_for(self.dut.tl_a_ready_o), "TL-UL write A-channel handshake timeout"

        self.dut.tl_a_valid_i.value = 0
        self.dut.tl_a_opcode_i.value = 0
        self.dut.tl_a_address_i.value = 0
        self.dut.tl_a_data_i.value = 0

        assert await self._wait_for(self.dut.tl_d_valid_o), "TL-UL write D-channel response timeout"
        d_error = _logic_to_int(self.dut.tl_d_error_o.value)
        if not allow_error:
            assert d_error == 0, "TL-UL write returned d_error"

        await RisingEdge(self.clk)
        self.dut.tl_d_ready_i.value = 0
        return d_error

    async def read_reg(self, addr, source=0):
        self.dut.tl_a_valid_i.value = 1
        self.dut.tl_a_opcode_i.value = 4  # Get
        self.dut.tl_a_address_i.value = addr
        self.dut.tl_a_data_i.value = 0
        self.dut.tl_a_mask_i.value = 0xF
        self.dut.tl_a_source_i.value = source
        self.dut.tl_a_size_i.value = 2
        self.dut.tl_d_ready_i.value = 1

        await RisingEdge(self.clk)
        assert await self._wait_for(self.dut.tl_a_ready_o), "TL-UL read A-channel handshake timeout"

        self.dut.tl_a_valid_i.value = 0
        self.dut.tl_a_opcode_i.value = 0
        self.dut.tl_a_address_i.value = 0

        assert await self._wait_for(self.dut.tl_d_valid_o), "TL-UL read D-channel response timeout"
        assert _logic_to_int(self.dut.tl_d_error_o.value) == 0, "TL-UL read returned d_error"

        data = _logic_to_int(self.dut.tl_d_data_o.value) & 0xFFFFFFFF
        await RisingEdge(self.clk)
        self.dut.tl_d_ready_i.value = 0
        return data


def _hex32(value):
    return "0x{0:08X}".format(value & 0xFFFFFFFF)


def _iter_set_bits(mask):
    bit = 0
    value = mask & 0xFFFFFFFF
    while value:
        if value & 1:
            yield bit
        value >>= 1
        bit += 1


async def _setup(dut):
    cocotb.start_soon(Clock(dut.clk_i, 10, unit="ns").start())
    await RisingEdge(dut.clk_i)

    drv = TlUlDriver(dut)
    await drv.reset()
    return drv


@cocotb.test()
async def test_csr_reset_values(dut):
    """Verify reset value of every readable register."""

    drv = await _setup(dut)
    checked = 0

    for reg in REGISTERS:
        if not reg["readable"]:
            dut._log.debug("Skipping reset read for write-only register %s", reg["name"])
            continue

        if not reg["reset_stable"]:
            dut._log.debug("Skipping strict reset check for volatile register %s", reg["name"])
            continue

        value = await drv.read_reg(reg["offset"])
        expected = reg["reset"] & 0xFFFFFFFF
        assert value == expected, (
            "{0} reset mismatch: got {1}, expected {2}".format(
                reg["name"], _hex32(value), _hex32(expected)
            )
        )
        checked += 1

    assert checked > 0, "No readable registers were checked for reset values"


@cocotb.test()
async def test_csr_rw_ro_access(dut):
    """Verify RW and RO access behavior based on generated masks."""

    drv = await _setup(dut)

    for reg in REGISTERS:
        offset = reg["offset"]

        if reg["rw_mask"] and reg["rw_stable"]:
            for pattern in PATTERNS:
                write_val = pattern & reg["rw_mask"]
                await drv.write_reg(offset, write_val)
                if reg["readable"]:
                    readback = await drv.read_reg(offset)
                    assert (readback & reg["rw_mask"]) == write_val, (
                        "{0} RW mismatch: wrote {1}, read {2}, mask {3}".format(
                            reg["name"],
                            _hex32(write_val),
                            _hex32(readback),
                            _hex32(reg["rw_mask"]),
                        )
                    )

        elif reg["rw_mask"] and not reg["rw_stable"]:
            dut._log.debug("Skipping strict RW readback for side-effect register %s", reg["name"])

        if reg["ro_mask"] and reg["readable"]:
            if not reg["ro_stable"]:
                dut._log.debug("Skipping strict RO immutability check for volatile register %s", reg["name"])
                continue

            before = await drv.read_reg(offset)
            probe = ((before ^ 0xFFFFFFFF) & reg["writable_mask"]) | 0xFFFFFFFF
            d_error = await drv.write_reg(offset, probe, allow_error=True)
            if d_error:
                dut._log.debug("RO write to %s returned d_error (acceptable)", reg["name"])
            after = await drv.read_reg(offset)
            assert (after & reg["ro_mask"]) == (before & reg["ro_mask"]), (
                "{0} RO bits changed after write: before={1} after={2} ro_mask={3}".format(
                    reg["name"],
                    _hex32(before),
                    _hex32(after),
                    _hex32(reg["ro_mask"]),
                )
            )


async def _prime_w1c_bits(drv, reg):
    """Attempt to set W1C bits using a companion TEST register when available."""

    setter_offset = W1C_SETTERS.get(reg["name"])
    if setter_offset is not None:
        await drv.write_reg(setter_offset, reg["w1c_mask"])


@cocotb.test()
async def test_csr_w1c_behavior(dut):
    """Verify write-0 keeps W1C bits and write-1 clears set W1C bits."""

    drv = await _setup(dut)
    checked = 0

    for reg in REGISTERS:
        mask = reg["w1c_mask"]
        if not mask or not reg["readable"]:
            continue

        await _prime_w1c_bits(drv, reg)

        before = await drv.read_reg(reg["offset"])
        await drv.write_reg(reg["offset"], 0)
        after_zero = await drv.read_reg(reg["offset"])

        if (after_zero & mask) != (before & mask):
            dut._log.warning(
                "%s W1C write-0 changed bits (tolerated for live status): before=%s after=%s mask=%s",
                reg["name"],
                _hex32(before),
                _hex32(after_zero),
                _hex32(mask),
            )

        set_bits = after_zero & mask
        if set_bits == 0:
            dut._log.warning(
                "Skipping strict W1C clear check for %s (no set bits observed)",
                reg["name"],
            )
            continue

        await drv.write_reg(reg["offset"], set_bits)
        after_clear = await drv.read_reg(reg["offset"])
        uncleared = after_clear & set_bits
        if uncleared != 0:
            dut._log.warning(
                "%s W1C bits remained set after clear (tolerated for live/persistent condition): wrote=%s read=%s uncleared=%s",
                reg["name"],
                _hex32(set_bits),
                _hex32(after_clear),
                _hex32(uncleared),
            )
        else:
            checked += 1

    if checked == 0:
        dut._log.warning("No W1C register had observable set bits during this run")


@cocotb.test()
async def test_csr_bit_isolation(dut):
    """Walking-1 and walking-0 checks across each RW register's writable bits."""

    drv = await _setup(dut)
    checks = 0

    for reg in REGISTERS:
        mask = reg["rw_mask"]
        if not mask or not reg["readable"] or not reg["rw_stable"]:
            continue

        # Walking-1
        for bit in _iter_set_bits(mask):
            expected = 1 << bit
            await drv.write_reg(reg["offset"], expected)
            readback = await drv.read_reg(reg["offset"])
            assert (readback & mask) == expected, (
                "{0} walking-1 failed at bit {1}: read {2} mask {3}".format(
                    reg["name"], bit, _hex32(readback), _hex32(mask)
                )
            )
            checks += 1

        # Walking-0
        for bit in _iter_set_bits(mask):
            expected = mask & ~(1 << bit)
            await drv.write_reg(reg["offset"], expected)
            readback = await drv.read_reg(reg["offset"])
            assert (readback & mask) == expected, (
                "{0} walking-0 failed at bit {1}: read {2} mask {3}".format(
                    reg["name"], bit, _hex32(readback), _hex32(mask)
                )
            )
            checks += 1

        await drv.write_reg(reg["offset"], reg["reset"] & mask)

    assert checks > 0, "No RW bit-isolation checks were executed"


@cocotb.test()
async def test_csr_address_decode(dut):
    """Check for address aliasing across stable RW configuration registers."""

    drv = await _setup(dut)
    candidates = [
        reg
        for reg in REGISTERS
        if reg["decode_candidate"] and reg["rw_mask"] != 0 and reg["readable"]
    ]

    if len(candidates) < 2:
        dut._log.warning("Not enough decode-safe RW registers for alias test")
        return

    expected = {}
    for index, reg in enumerate(candidates, start=1):
        pattern = ((index * 0x11111111) ^ 0xA5A5A5A5) & reg["rw_mask"]
        if pattern == 0:
            for bit in _iter_set_bits(reg["rw_mask"]):
                pattern = 1 << bit
                break
        await drv.write_reg(reg["offset"], pattern)
        expected[reg["name"]] = pattern

    for reg in candidates:
        readback = await drv.read_reg(reg["offset"])
        assert (readback & reg["rw_mask"]) == expected[reg["name"]], (
            "Address decode mismatch for {0}: expected {1} got {2}".format(
                reg["name"],
                _hex32(expected[reg["name"]]),
                _hex32(readback),
            )
        )

